[project]
name = "test-django-tasks-libs"
version = "0.1.0"
description = "App Django para comparar 7 libs de task queue com PostgreSQL como broker"
requires-python = ">=3.12"
dependencies = [
    "chancy[cli,django]>=0.25.1",
    "django==5.2.*",
    "django-dramatiq>=0.15.0",
    "django-huey-monitor>=0.10.1",
    "django-q2>=1.11.0",
    "django-tasks-db>=0.12.0",
    "dramatiq-pg>=0.12.0",
    "huey>=3.3.4",
    "peewee>=4.3.0",
    "procrastinate[django]>=3.9.0",
    "psycopg[binary]>=3.3.4",
    "psycopg2-binary<3",
    "taskito[django,postgres]>=0.22.0",
]
