# Generated by Django 5.2.17 on 2026-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('huey', 'Huey'), ('dramatiq', 'Dramatiq'), ('q2', 'Django-Q2'), ('tasks_db', 'Django Tasks (DB)'), ('chancy', 'Chancy'), ('procrastinate', 'Procrastinate'), ('flexiq', 'FlexiQ')], db_index=True, max_length=20),
        ),
    ]
